services:
  topimmo-postgres:
    image: postgres:16-alpine
    container_name: topimmo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: topimmo_local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - topimmo_pg_data:/var/lib/postgresql/data

volumes:
  topimmo_pg_data:
